### ISSUE TITLE
Can't reproduce the results of ROID on imagenet-c

### ISSUE THREAD

**Issue by txz741** [mariodoebler/test-time-adaptation#4]
Awesome job!
But I still have some problems on reproducing the results of ROID on imagenet-c. The original detailed results of ROID on imagenet-c are shown in Table 12 if I understand correctly.
![1688312610177](https://github.com/mariodoebler/test-time-adaptation/assets/30717636/959abb81-9f61-4765-b52f-7fe81d01075a)
However, when I try to reproduce the experiments by the script:
`CUDA_VISIBLE_DEVICES=0 python test_time.py --cfg cfgs/imagenet_c/roid.yaml`
the final results are far behind than that in the paper. The log file is attached below.
[roid_230702_231218.txt](https://github.com/mariodoebler/test-time-adaptation/files/11929969/roid_230702_231218.txt)
I don't know what's going wrong. By the way, the results of cifar10c and cifar100c are in consistent with that in the paper.
Can you help find out the reason?
Thanks again for your excellent job!
Best Regards.

**Comment by mariodoebler** [comment]
Hi @txz741,

thanks! In your case it's using the resnet50 from timm and not the checkpoint from torchvision. Are you using the provided environment? It seems like you're using, e.g., the wrong PyTorch Version (1.10.0 instead of 1.13.1). Make sure you have torchvision 0.14.1 installed as well.

Regarding the CIFAR-C results: I'm not sure, if I understood it correctly. Are they consistent with the paper or inconsistent? Thanks!

All the best,
Mario

**Comment by txz741** [comment]
> 

Wonderful! Now the results of ROID on imagenet-c can be reproduced perfectly! I may never address the issue without your help since I may never suspect the environments and pretrained models.

Regarding the CIFAR-C results, they are consistent with the paper (sorry for my expression before), because the pretrained models of CIFAR-C are adopted from the official google drive links of RobustBench, no confusion about choosing timm or torchvision.

Thanks again for your timely and accurate response!

Best regards,
txz741
