### ISSUE TITLE
mixed domains TTA setting

### ISSUE THREAD

**Issue by Fenghao1995** [mariodoebler/test-time-adaptation#8]
Nice work for universal TTA. But I have a little problem. For ImageNet-C, how to keep per corruption with 50000 samples in the mixed domains TTA setting. By setting "_C.CORRUPTION.NUM_EX = -1", we can only use 75,000 (5000 per corruption *15 )samples.

**Comment by RobMarsden** [comment]
Hi @Fenghao1995, 

thank you for your interest in our work. If you want to work with IN-C in the "mixed_domains" setting with the full 50000 samples per domain, just set CORRUPTION.NUM_EX = 750000. (Short explanation: If you set CORRUPTION.NUM_EX != -1 for IN-C, the 50k sequence will be loaded instead of the default 5k sequence from robustbench. Since the "mixed_domains" setting is taken into account, all 15 * 50k samples are loaded first before the test sequence is shortened to the desired length). 

All the best,
Rob

**Comment by Fenghao1995** [comment]
Thanks for your quick reply!

**Comment by Fenghao1995** [comment]
Thanks for your quick reply!
